apiVersion: v1
kind: Service
metadata:
  name: system-metrics-service-nodeport
  labels:
    app: system-metrics-service
spec:
  type: NodePort
  selector:
    app: system-metrics-service
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
