apiVersion: v1
kind: Service
metadata:
  name: system-metrics-service
  labels:
    app: system-metrics-service
spec:
  type: ClusterIP
  selector:
    app: system-metrics-service
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80